### ISSUE TITLE
Video glitch

### ISSUE THREAD

**Issue by DBarbedillo** [lucataco/banana-damo-text-to-video#1]
Hi, I ran the code using the "prod.py" example, and the video was saved successfully on my computer as "output.mp4" but when opening the mp4 I only see a glitchy screen that changes every time I open the file. What could be the problem?

I'm attaching some screenshots in order to display how the video looks

<img width="271" alt="Screen Shot 2023-04-04 at 17 10 08" src="https://user-images.githubusercontent.com/81596780/229943405-bcb5db76-3806-4b7a-936e-b4d91afa5941.png">
<img width="264" alt="Screen Shot 2023-04-04 at 17 12 09" src="https://user-images.githubusercontent.com/81596780/229943407-596a757f-e907-4d61-ac05-b57e8a20ec13.png">
<img width="262" alt="Screen Shot 2023-04-04 at 17 12 43" src="https://user-images.githubusercontent.com/81596780/229943410-ad0a45cd-0895-46be-a9a5-5eda99fbe0fd.png">

**Comment by lucataco** [comment]
Did you try a different video player, like VLC?

**Comment by DBarbedillo** [comment]
In Quicktime player, it didn't work but I just tried playing it in VLC player and it did work. Thank you for the suggestion!
